### ISSUE TITLE
Merge rules

### ISSUE THREAD

**Issue by jgiven100** [geomechanics/mpm-examples#2]
@geomechanics-berkeley lets update the merge rules in this repo! I think 1 approval is good.

**Comment by jgiven100** [comment]
@geomechanics-berkeley maybe also rules about who can make a branch? I'm not sure how the [geomechanics mpm](https://github.com/geomechanics/mpm) is currently set up

**Comment by geomechanics-berkeley** [comment]
Thank you for your suggestion, Mr. Given. The change has been made!
